name: 'Setup Android'
description: 'Setting up Android & JDK'
inputs:
  key-store-file-content:
    description: ''
    required: true
  key-store-password:
    description: ''
    required: true
  signing-key-alias:
    description: ''
    required: true
  signing-key-password:
    description: ''
    required: true  
  github-username:
    type: string
    required: true
  github-token:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - uses: roadsurfer-com/actions/setup-environment@main
    - name: Setup Java Version
      id: setup-java
      shell: bash
      run: |
        java_version=$JAVA_VERSION 
        java_distribution=$JAVA_DISTRIBUTION 
        
        echo "java-version=$java_version" >> $GITHUB_OUTPUT
        echo "java-distribution=$java_distribution" >> $GITHUB_OUTPUT
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ steps.setup-java.outputs.java-version }}
        distribution: ${{ steps.setup-java.outputs.java-distribution }}
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Setup Maven Secrets
      shell: bash
      run: |
        echo GITHUB_USERNAME=${{ inputs.github-username }} >> $GITHUB_ENV
        echo GITHUB_TOKEN=${{ inputs.github-token }} >> $GITHUB_ENV
    - name: Setup Android Signing Keys
      shell: bash
      run: |
        KEY_STORE_PATH="${RUNNER_TEMP}"/keystore.jks
        echo ${{ inputs.key-store-file-content }} | base64 -d > "$KEY_STORE_PATH" 

        echo ANDROID_KEYSTORE_PATH="$KEY_STORE_PATH" >> $GITHUB_ENV
        echo ANDROID_KEYSTORE_PASSWORD=${{ inputs.key-store-password }} >> $GITHUB_ENV
        echo ANDROID_SIGNING_KEY_ALIAS=${{ inputs.signing-key-alias }} >> $GITHUB_ENV
        echo ANDROID_SIGNING_KEY_PASSWORD=${{ inputs.signing-key-password }} >> $GITHUB_ENV
